"""update schema

Revision ID: 7cbfe9ad4c40
Revises: 9f6a1c8b7e21
Create Date: 2026-03-22 14:37:33.473566
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7cbfe9ad4c40'
down_revision = '9f6a1c8b7e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
