"""update schema

Revision ID: cb301addd2d0
Revises: 7cbfe9ad4c40
Create Date: 2026-03-22 15:33:56.247674
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'cb301addd2d0'
down_revision = '7cbfe9ad4c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
