"""update schema

Revision ID: eb540d57900a
Revises: 0002_documents_and_admin
Create Date: 2026-03-22 13:48:39.512998
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'eb540d57900a'
down_revision = '0002_documents_and_admin'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_storage_key'), table_name='documents')
    op.create_unique_constraint(None, 'documents', ['storage_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_index(op.f('ix_documents_storage_key'), 'documents', ['storage_key'], unique=True)
    # ### end Alembic commands ###
